### ISSUE TITLE
Ensure `registry` option is enforced even when `package-lock.json` has different resolved

### ISSUE THREAD

**Issue by darcyclarke** [npm/npm-registry-fetch#7] opened 2019-09-12 17:31 UTC
There seems to be some confusion around whether the `package-lock.json` file enforces the destination of the package that is fetched based on the `resolved` field. 

Based on some historical context (ref [1](https://support.sonatype.com/hc/en-us/articles/213465048-Why-does-npm-client-need-access-to-URLs-other-than-my-private-registry-) & [2](https://github.com/npm/npm/issues/16849#issuecomment-312442508)), I'd like us to test that we do, indeed, respect the `registry` option when set in `.npmrc` or `--registry` and potentially add a test for the scenario where a lock file has disparate references to the provided registry (ref [current pickRegistry() tests](https://github.com/npm/npm-registry-fetch/blob/latest/test/index.js#L347-L412)).

- [x] Test functionality as it stands today (and confirm the above is true)
- [x] Write a new test to explicitly test this scenario (ie. a mismatch between `resolved` paths in `package-lock.json` vs. a defined `registry` option)
- [x] Update [docs](https://github.com/npm/cli/blob/ab0f0260e5b6333f98062fb2d9f4f9954d3ee6cd/doc/misc/npm-registry.md) to explicitly communicate this functionality more thoroughly

**Comment by ruyadorno** [comment] 2019-09-13 19:02
A hacky e2e-test-poc was put in place using a fork of **npm-registry-mock** in which we validate this behavior in a reproducible manner: https://github.com/npm/npm-registry-mock/pull/35

**Comment by ruyadorno** [comment] 2019-09-17 21:44
Closing this since we already got all the answers we wanted 😊

**Closed by ruyadorno** 2019-09-17 21:44 UTC
Labels: enhancement, help wanted, question
